import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/Layout";
import ReduxProvider from "@/provider/ReduxProvider";

export const metadata: Metadata = {
  title: "Floratio Lib",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
    shortcut: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (typeof window !== 'undefined') {
    // client-safe code
  }
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Layout>{children}</Layout>
        </ReduxProvider>        
      </body>
    </html>
  );
}
